export type RoomItem = {
  _id: string;
  title: string;
  location: string;
  rent: number;
  deposit: number;
  roomType: string;
  furnishing: string;
  rating: number;
  reviewCount: number;
  images: string[];
  description: string;
  address: string;
  status: string;
  ownerDetails?: { isVerified?: boolean; verificationStatus?: string; name?: string };
};

export const locations = [
  'Lalpur',
  'Ratu Road',
  'Harmu',
  'Morabadi',
  'Kanke Road',
  'Bariatu',
  'Doranda',
  'Main Road',
  'Upper Bazar',
  'Kokar'
];

export const demoRooms: RoomItem[] = [
  {
    _id: '1',
    title: 'Spacious Single Room near HEC',
    location: 'Lalpur',
    rent: 4800,
    deposit: 12000,
    roomType: 'Single Room',
    furnishing: 'Fully Furnished',
    rating: 4.8,
    reviewCount: 18,
    status: 'approved',
    images: [
      'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=1200&q=80'
    ],
    description: 'Comfortable single room for students near HEC and engineering colleges.',
    address: 'Lalpur Main Lane, Ranchi',
    ownerDetails: { isVerified: true, verificationStatus: 'verified', name: 'Ranchi Homes' }
  },
  {
    _id: 'shared-1',
    title: 'Shared Room with Balcony and Study Corner',
    location: 'Harmu',
    rent: 5600,
    deposit: 14000,
    roomType: 'Shared Room',
    furnishing: 'Semi Furnished',
    rating: 4.6,
    reviewCount: 16,
    status: 'approved',
    images: [
      'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=1200&q=80'
    ],
    description: 'Budget-friendly shared room with a bright balcony, shared kitchen, and a student-friendly layout.',
    address: 'Harmu Road, Ranchi',
    ownerDetails: { isVerified: true, verificationStatus: 'verified', name: 'StudyNest' }
  },
  {
    _id: 'family-flat-1',
    title: 'Family Flat with 2 Bedrooms',
    location: 'Doranda',
    rent: 9800,
    deposit: 22000,
    roomType: 'Family Flat',
    furnishing: 'Fully Furnished',
    rating: 4.8,
    reviewCount: 14,
    status: 'approved',
    images: [
      'https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&q=80'
    ],
    description: 'Fully furnished family flat with space, privacy, and secure living for students or working professionals.',
    address: 'Doranda Road, Ranchi',
    ownerDetails: { isVerified: true, verificationStatus: 'verified', name: 'Urban Living' }
  },
  {
    _id: '2',
    title: 'Budget PG for Girls near Ratu Road',
    location: 'Ratu Road',
    rent: 5200,
    deposit: 13000,
    roomType: 'PG Room',
    furnishing: 'Semi Furnished',
    rating: 4.7,
    reviewCount: 12,
    status: 'approved',
    images: [
      'https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80'
    ],
    description: 'Safe PG with shared facilities and secure access for students.',
    address: 'Ratu Road, Ranchi',
    ownerDetails: { isVerified: true, verificationStatus: 'verified', name: 'SafeStay PG' }
  },
  {
    _id: '3',
    title: 'Modern Double Sharing Room',
    location: 'Harmu',
    rent: 6500,
    deposit: 15000,
    roomType: 'Double Room',
    furnishing: 'Fully Furnished',
    rating: 4.9,
    reviewCount: 21,
    status: 'approved',
    images: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80'
    ],
    description: 'Double sharing room with AC, WiFi, and secure gated entry.',
    address: 'Harmu Housing Colony, Ranchi',
    ownerDetails: { isVerified: false, verificationStatus: 'pending', name: 'Harmu Living' }
  },
  {
    _id: '4',
    title: 'Studio Apartment for Students',
    location: 'Morabadi',
    rent: 7800,
    deposit: 18000,
    roomType: 'Studio Room',
    furnishing: 'Fully Furnished',
    rating: 4.6,
    reviewCount: 10,
    status: 'approved',
    images: [
      'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=1200&q=80'
    ],
    description: 'Compact studio with modern fixtures and cozy ambience.',
    address: 'Morabadi Road, Ranchi',
    ownerDetails: { isVerified: true, verificationStatus: 'verified', name: 'Urban Nest' }
  },
  {
    _id: '5',
    title: 'Bright Single Room near Lalpur Chowk',
    location: 'Lalpur',
    rent: 4200,
    deposit: 10000,
    roomType: 'Single Room',
    furnishing: 'Semi Furnished',
    rating: 4.5,
    reviewCount: 14,
    status: 'approved',
    images: ['https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?auto=format&fit=crop&w=1200&q=80'],
    description: 'Well-lit student room close to shops, transport, and daily essentials.',
    address: 'Lalpur Chowk, Ranchi',
    ownerDetails: { isVerified: true, verificationStatus: 'verified', name: 'City Nest' }
  },
  {
    _id: '6',
    title: 'Affordable PG Room in Lalpur',
    location: 'Lalpur',
    rent: 5800,
    deposit: 12000,
    roomType: 'PG Room',
    furnishing: 'Fully Furnished',
    rating: 4.6,
    reviewCount: 16,
    status: 'approved',
    images: ['https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80'],
    description: 'Managed PG with WiFi, housekeeping, and secure entry.',
    address: 'Circular Road, Lalpur, Ranchi',
    ownerDetails: { isVerified: true, verificationStatus: 'verified', name: 'Student Stay' }
  },
  {
    _id: '7',
    title: 'Comfortable Single Room on Ratu Road',
    location: 'Ratu Road',
    rent: 4800,
    deposit: 11000,
    roomType: 'Single Room',
    furnishing: 'Fully Furnished',
    rating: 4.4,
    reviewCount: 11,
    status: 'approved',
    images: ['https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80'],
    description: 'Quiet furnished room with easy access to the main road.',
    address: 'Ratu Road Extension, Ranchi',
    ownerDetails: { isVerified: false, verificationStatus: 'pending', name: 'Ratu Homes' }
  },
  {
    _id: '8',
    title: 'Premium Double Room near Ratu Road',
    location: 'Ratu Road',
    rent: 7200,
    deposit: 16000,
    roomType: 'Double Room',
    furnishing: 'Fully Furnished',
    rating: 4.7,
    reviewCount: 19,
    status: 'approved',
    images: ['https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&q=80'],
    description: 'Spacious sharing room with balcony, WiFi, and power backup.',
    address: 'Ratu Road Main Lane, Ranchi',
    ownerDetails: { isVerified: true, verificationStatus: 'verified', name: 'Comfort Corner' }
  },
  {
    _id: '9',
    title: 'Furnished Single Room in Harmu',
    location: 'Harmu',
    rent: 4600,
    deposit: 10000,
    roomType: 'Single Room',
    furnishing: 'Semi Furnished',
    rating: 4.5,
    reviewCount: 13,
    status: 'approved',
    images: ['https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=1200&q=80'],
    description: 'Peaceful room in a residential colony with nearby markets.',
    address: 'Harmu Road, Ranchi',
    ownerDetails: { isVerified: true, verificationStatus: 'verified', name: 'Harmu Living' }
  },
  {
    _id: '10',
    title: 'Modern PG Space in Harmu',
    location: 'Harmu',
    rent: 5900,
    deposit: 13000,
    roomType: 'PG Room',
    furnishing: 'Fully Furnished',
    rating: 4.6,
    reviewCount: 17,
    status: 'approved',
    images: ['https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80'],
    description: 'Student-friendly PG with meals, cleaning, and common areas.',
    address: 'Harmu Housing Colony, Ranchi',
    ownerDetails: { isVerified: true, verificationStatus: 'verified', name: 'Harmu Homes' }
  },
  {
    _id: '11',
    title: 'Quiet Single Room in Morabadi',
    location: 'Morabadi',
    rent: 5500,
    deposit: 13000,
    roomType: 'Single Room',
    furnishing: 'Fully Furnished',
    rating: 4.7,
    reviewCount: 15,
    status: 'approved',
    images: ['https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?auto=format&fit=crop&w=1200&q=80'],
    description: 'Calm furnished room close to parks, cafes, and coaching centres.',
    address: 'Morabadi Ground Road, Ranchi',
    ownerDetails: { isVerified: true, verificationStatus: 'verified', name: 'Green View Rooms' }
  },
  {
    _id: '12',
    title: 'Executive Studio near Morabadi',
    location: 'Morabadi',
    rent: 8500,
    deposit: 20000,
    roomType: 'Studio Room',
    furnishing: 'Fully Furnished',
    rating: 4.8,
    reviewCount: 22,
    status: 'approved',
    images: ['https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80'],
    description: 'Private studio with a kitchenette, workspace, and attached bath.',
    address: 'Morabadi Road, Ranchi',
    ownerDetails: { isVerified: true, verificationStatus: 'verified', name: 'Urban Nest' }
  },
  {
    _id: '13',
    title: 'Student Room near Kanke Road',
    location: 'Kanke Road',
    rent: 4300,
    deposit: 10000,
    roomType: 'Single Room',
    furnishing: 'Semi Furnished',
    rating: 4.4,
    reviewCount: 9,
    status: 'approved',
    images: ['https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=1200&q=80'],
    description: 'Affordable room with a study desk and reliable power backup.',
    address: 'Kanke Road, Ranchi',
    ownerDetails: { isVerified: false, verificationStatus: 'pending', name: 'Kanke Stay' }
  },
  {
    _id: '14',
    title: 'Sharing Room near Kanke Road',
    location: 'Kanke Road',
    rent: 6200,
    deposit: 14000,
    roomType: 'Double Room',
    furnishing: 'Fully Furnished',
    rating: 4.6,
    reviewCount: 12,
    status: 'approved',
    images: ['https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&q=80'],
    description: 'Clean double room near colleges, bus routes, and food spots.',
    address: 'Kanke Road Main Lane, Ranchi',
    ownerDetails: { isVerified: true, verificationStatus: 'verified', name: 'Campus Homes' }
  },
  {
    _id: '15',
    title: 'Cozy Single Room in Bariatu',
    location: 'Bariatu',
    rent: 4700,
    deposit: 10000,
    roomType: 'Single Room',
    furnishing: 'Semi Furnished',
    rating: 4.5,
    reviewCount: 10,
    status: 'approved',
    images: ['https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=1200&q=80'],
    description: 'Comfortable room in a quiet neighbourhood with good ventilation.',
    address: 'Bariatu Road, Ranchi',
    ownerDetails: { isVerified: true, verificationStatus: 'verified', name: 'Bariatu Homes' }
  },
  {
    _id: '16',
    title: 'Bariatu PG with Modern Amenities',
    location: 'Bariatu',
    rent: 6800,
    deposit: 15000,
    roomType: 'PG Room',
    furnishing: 'Fully Furnished',
    rating: 4.7,
    reviewCount: 18,
    status: 'approved',
    images: ['https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80'],
    description: 'Managed PG with food options, cleaning, and high-speed WiFi.',
    address: 'Bariatu Housing Colony, Ranchi',
    ownerDetails: { isVerified: true, verificationStatus: 'verified', name: 'Bariatu Stay' }
  },
  {
    _id: '17',
    title: 'Private Room close to Doranda Market',
    location: 'Doranda',
    rent: 5200,
    deposit: 12000,
    roomType: 'Single Room',
    furnishing: 'Fully Furnished',
    rating: 4.6,
    reviewCount: 14,
    status: 'approved',
    images: ['https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80'],
    description: 'Ready-to-move room near markets, transport, and office areas.',
    address: 'Doranda Market Road, Ranchi',
    ownerDetails: { isVerified: true, verificationStatus: 'verified', name: 'Doranda Homes' }
  },
  {
    _id: '18',
    title: 'Spacious PG Room in Doranda',
    location: 'Doranda',
    rent: 7600,
    deposit: 17000,
    roomType: 'PG Room',
    furnishing: 'Fully Furnished',
    rating: 4.7,
    reviewCount: 20,
    status: 'approved',
    images: ['https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=1200&q=80'],
    description: 'Premium PG with attached bath, meals, and housekeeping.',
    address: 'Doranda Main Road, Ranchi',
    ownerDetails: { isVerified: true, verificationStatus: 'verified', name: 'Airport View Stay' }
  },
  {
    _id: '19',
    title: 'Budget Single Room on Main Road',
    location: 'Main Road',
    rent: 3900,
    deposit: 9000,
    roomType: 'Single Room',
    furnishing: 'Semi Furnished',
    rating: 4.3,
    reviewCount: 8,
    status: 'approved',
    images: ['https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?auto=format&fit=crop&w=1200&q=80'],
    description: 'Value-friendly room in the heart of Ranchi with easy commuting.',
    address: 'Main Road, Ranchi',
    ownerDetails: { isVerified: false, verificationStatus: 'pending', name: 'Central Rooms' }
  },
  {
    _id: '20',
    title: 'Modern Double Room on Main Road',
    location: 'Main Road',
    rent: 7000,
    deposit: 16000,
    roomType: 'Double Room',
    furnishing: 'Fully Furnished',
    rating: 4.6,
    reviewCount: 16,
    status: 'approved',
    images: ['https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&q=80'],
    description: 'Bright sharing room close to offices, cafes, and public transport.',
    address: 'Main Road Central Lane, Ranchi',
    ownerDetails: { isVerified: true, verificationStatus: 'verified', name: 'Central Living' }
  },
  {
    _id: '21',
    title: 'Affordable Room in Upper Bazar',
    location: 'Upper Bazar',
    rent: 4400,
    deposit: 10000,
    roomType: 'Single Room',
    furnishing: 'Semi Furnished',
    rating: 4.4,
    reviewCount: 11,
    status: 'approved',
    images: ['https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80'],
    description: 'Practical room near shopping streets and everyday conveniences.',
    address: 'Upper Bazar, Ranchi',
    ownerDetails: { isVerified: true, verificationStatus: 'verified', name: 'Bazar Homes' }
  },
  {
    _id: '22',
    title: 'Fully Furnished PG in Upper Bazar',
    location: 'Upper Bazar',
    rent: 6100,
    deposit: 14000,
    roomType: 'PG Room',
    furnishing: 'Fully Furnished',
    rating: 4.5,
    reviewCount: 13,
    status: 'approved',
    images: ['https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80'],
    description: 'Convenient PG with WiFi, laundry access, and secure entry.',
    address: 'Upper Bazar Main Lane, Ranchi',
    ownerDetails: { isVerified: true, verificationStatus: 'verified', name: 'Bazar Stay' }
  },
  {
    _id: '23',
    title: 'Peaceful Single Room in Kokar',
    location: 'Kokar',
    rent: 4100,
    deposit: 9000,
    roomType: 'Single Room',
    furnishing: 'Semi Furnished',
    rating: 4.5,
    reviewCount: 9,
    status: 'approved',
    images: ['https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=1200&q=80'],
    description: 'Quiet and affordable room with convenient city access.',
    address: 'Kokar Industrial Area Road, Ranchi',
    ownerDetails: { isVerified: false, verificationStatus: 'pending', name: 'Kokar Rooms' }
  },
  {
    _id: '24',
    title: 'Comfortable Studio in Kokar',
    location: 'Kokar',
    rent: 7800,
    deposit: 18000,
    roomType: 'Studio Room',
    furnishing: 'Fully Furnished',
    rating: 4.7,
    reviewCount: 15,
    status: 'approved',
    images: ['https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80'],
    description: 'Private studio with a modern interior and dedicated workspace.',
    address: 'Kokar Main Road, Ranchi',
    ownerDetails: { isVerified: true, verificationStatus: 'verified', name: 'Kokar Living' }
  }
];

export const navItems = ['Home', 'Find Rooms', 'Locations', 'Map', 'About'];
